import { Activity, CalendarDays, CheckCircle2, ChevronRight, Heart, Image, Link2, MessageCircle, Sparkles, Users } from 'lucide-react';
import type { Pictogram, TutorHomeData, TutorHomeLinkedUser } from '@/data/api';
import type { TutorAggregateActivity, TutorAggregateEmotion } from '@/lib/tutorHomeModel';
import { buildTutorHomeViewModel, tutorRelativeTime } from '@/lib/tutorHomeModel';
import type { TutorAggregateEvent } from '@/lib/tutorEventAggregation';
import type { TutorTab } from '@/components/tutor/TutorNavigation';

interface Props {
  userName: string;
  data: TutorHomeData;
  linkedUsers: TutorHomeLinkedUser[];
  activities: TutorAggregateActivity[];
  emotions: TutorAggregateEmotion[];
  events: TutorAggregateEvent[];
  pictograms: Pictogram[];
  onNavigate: (tab: TutorTab) => void;
  onOpenDetail: (id: string) => void;
}

export default function TutorHome(props: Props) {
  const model = buildTutorHomeViewModel(props.data, props.linkedUsers, props.activities, props.emotions, props.events);
  return <div className="space-y-5 lg:space-y-6">
    <HomeGreeting userName={props.userName} />
    <QuickActions onNavigate={props.onNavigate} />
    <div className="grid gap-5 xl:grid-cols-2">
      <LinkedSummary model={model} linkedCount={props.linkedUsers.length} activityCount={props.activities.length} onOpen={() => props.onNavigate('reports')} />
      <UpcomingEvents events={model.upcomingEvents} onOpen={() => props.onNavigate('calendar')} />
      <RecentActivity items={model.recentItems} onOpenActivities={() => props.onNavigate('activities')} onOpenDetail={props.onOpenDetail} />
      <PictogramTools pictograms={props.pictograms} onCreate={() => props.onNavigate('pictograms')} onExplore={() => props.onNavigate('pictogramCatalog')} />
    </div>
  </div>;
}

function HomeGreeting({ userName }: { userName: string }) { return <section><h1 className="font-heading text-3xl font-bold tracking-tight text-foreground sm:text-4xl">Buen día, {userName.split(' ')[0]}</h1><p className="mt-2 text-sm text-muted-foreground sm:text-base">Todo lo importante para acompañar, organizar y conectar, en un solo lugar.</p></section>; }

function QuickActions({ onNavigate }: { onNavigate: Props['onNavigate'] }) { return <section aria-label="Acciones rápidas" className="hidden grid-cols-2 gap-3 lg:grid lg:grid-cols-4"><QuickAction icon={CheckCircle2} label="Asignar actividad" onClick={() => onNavigate('activities')} /><QuickAction icon={CalendarDays} label="Agregar evento" onClick={() => onNavigate('calendar')} /><QuickAction icon={MessageCircle} label="Enviar mensaje" onClick={() => onNavigate('chat')} /><QuickAction icon={Link2} label="Vincular" onClick={() => onNavigate('connections')} /></section>; }

function LinkedSummary({ model, linkedCount, activityCount, onOpen }: { model: ReturnType<typeof buildTutorHomeViewModel>; linkedCount: number; activityCount: number; onOpen: () => void }) {
  const emotion = model.emotionPercentages;
  return <DashboardCard title="Resumen de vinculados" icon={Users} action="Ver detalle" onAction={onOpen}>{linkedCount === 0 ? <EmptyState text="Todavía no hay personas vinculadas." /> : <div className="grid gap-5 md:grid-cols-[1.25fr_.75fr]">
    <div><p className="mb-4 text-sm font-semibold text-foreground">Actividades por integrante</p><div className="space-y-4">{model.memberProgress.map(({ owner, done, total, percentage }) => <div key={owner.id} className="grid grid-cols-[minmax(88px,auto)_1fr_42px] items-center gap-3"><span className="flex min-w-0 items-center gap-2"><OwnerAvatar owner={owner} /><span className="truncate text-xs font-medium">{owner.name.split(' ')[0]}</span></span><span className="h-3 overflow-hidden rounded-full bg-primary/10"><span className="block h-full rounded-full bg-[linear-gradient(90deg,#8157d9,#a78bfa)]" style={{ width: `${percentage}%` }} /></span><span className="text-right text-xs font-bold tabular-nums">{done}/{total}</span></div>)}</div></div>
    <div className="flex flex-col items-center justify-center border-t border-border pt-5 md:border-l md:border-t-0 md:pl-5 md:pt-0"><p className="self-start text-sm font-semibold text-foreground">Registros emocionales</p>{model.emotionTotal ? <><div className="relative my-4 h-28 w-28 rounded-full" style={{ background: `conic-gradient(#80c783 0 ${emotion.high}%,#f3be59 ${emotion.high}% ${emotion.high + emotion.medium}%,#e99bb7 ${emotion.high + emotion.medium}% 100%)` }}><div className="absolute inset-4 flex items-center justify-center rounded-full bg-card"><span className="text-2xl font-bold">{model.emotionTotal}</span></div></div><div className="w-full space-y-1 text-xs"><Legend color="bg-emerald-500" label="Intensidad alta" value={emotion.high} /><Legend color="bg-amber-400" label="Media" value={emotion.medium} /><Legend color="bg-rose-400" label="Baja" value={emotion.low} /></div></> : <EmptyState text="Sin registros de los últimos 7 días." />}</div>
    <div className="grid grid-cols-3 gap-2 rounded-2xl border border-primary/10 bg-primary/[0.035] p-3 md:col-span-2"><Metric value={linkedCount} label="vinculados" /><Metric value={activityCount} label="actividades" /><Metric value={`${model.adherence}%`} label="adherencia" /></div>
  </div>}</DashboardCard>;
}

function UpcomingEvents({ events, onOpen }: { events: ReturnType<typeof buildTutorHomeViewModel>['upcomingEvents']; onOpen: () => void }) { return <DashboardCard title="Próximos eventos" icon={CalendarDays} action="Ver calendario" onAction={onOpen}><div className="divide-y divide-border">{events.map(event => <button key={`${event.userId}-${event.id}`} type="button" onClick={onOpen} className="grid min-h-16 w-full grid-cols-[72px_1fr_auto] items-center gap-3 py-2 text-left transition-colors hover:bg-primary/[0.025] focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-ring"><span className="text-xs font-semibold text-primary"><span className="block">{new Date(`${event.date}T12:00:00`).toLocaleDateString('es-AR', { day: '2-digit', month: 'short' })}</span><span>{event.time}</span></span><span className="min-w-0"><span className="block truncate text-sm font-semibold text-foreground">{event.title}</span><span className="block truncate text-xs text-muted-foreground">{event.description || event.type}</span></span><EventContext owner={event.owner} /></button>)}{events.length === 0 && <EmptyState text="No hay próximos eventos programados." />}</div></DashboardCard>; }

function RecentActivity({ items, onOpenActivities, onOpenDetail }: { items: ReturnType<typeof buildTutorHomeViewModel>['recentItems']; onOpenActivities: () => void; onOpenDetail: (id: string) => void }) { return <DashboardCard title="Actividad reciente" icon={Activity} action="Ver actividades" onAction={onOpenActivities}><div className="divide-y divide-border">{items.map(item => { const Icon = item.type === 'emotion' ? Heart : item.completed ? CheckCircle2 : Activity; const color = item.type === 'emotion' ? 'text-rose-500 bg-rose-50' : 'text-emerald-600 bg-emerald-50'; return <button type="button" key={item.id} onClick={() => onOpenDetail(item.owner.id)} aria-label={`Ver información de ${item.owner.name}: ${item.label}`} className="grid min-h-14 w-full grid-cols-[36px_1fr_auto] items-center gap-3 py-2 text-left transition-colors hover:bg-primary/[0.025] focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-ring"><span className={`flex h-9 w-9 items-center justify-center rounded-xl ${color}`}><Icon size={18} aria-hidden /></span><span className="min-w-0"><span className="block truncate text-sm font-semibold">{item.label}</span><span className="block truncate text-xs text-muted-foreground">{item.detail} · {item.type === 'emotion' ? 'Emociones' : 'Actividad'}</span></span><span className="flex items-center gap-3"><PersonChip owner={item.owner} /><span className="hidden min-w-16 text-right text-xs text-muted-foreground sm:block">{tutorRelativeTime(item.date)}</span><ChevronRight size={16} className="text-muted-foreground" aria-hidden /></span></button>; })}{items.length === 0 && <EmptyState text="Todavía no hay actividad reciente." />}</div></DashboardCard>; }

function PictogramTools({ pictograms, onCreate, onExplore }: { pictograms: Pictogram[]; onCreate: () => void; onExplore: () => void }) { return <DashboardCard title="Pictogramas" icon={Image} action="Ver todos" onAction={onExplore}><div className="grid gap-3 sm:grid-cols-2"><ToolCard icon={Sparkles} title="Crear con IA" text="Generá pictogramas a partir de una idea" onClick={onCreate} /><ToolCard icon={Image} title="Explorar pictogramas" text="Buscá por categorías y temas" onClick={onExplore} /></div>{pictograms.length ? <div className="mt-4 flex flex-wrap gap-2" aria-label="Pictogramas recientes">{pictograms.slice(0, 6).map(pic => <button key={pic.id} type="button" onClick={onExplore} className="flex h-16 w-16 items-center justify-center overflow-hidden rounded-xl border border-border bg-white p-1 focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-ring">{pic.imageUrl ? <img src={pic.imageUrl} alt={pic.name} loading="lazy" className="h-full w-full object-contain" /> : <span className="text-2xl" aria-label={pic.name}>{pic.emoji}</span>}</button>)}</div> : <p className="mt-4 text-sm text-muted-foreground">Todavía no hay pictogramas disponibles para mostrar.</p>}</DashboardCard>; }

function DashboardCard({ title, icon: Icon, action, onAction, children }: { title: string; icon: typeof Activity; action?: string; onAction?: () => void; children: React.ReactNode }) { return <section className="rounded-[26px] border border-white/80 bg-white/90 p-4 shadow-[0_12px_36px_rgba(70,45,96,.075)] backdrop-blur sm:p-5"><header className="mb-4 flex items-center gap-3"><span className="flex h-10 w-10 items-center justify-center rounded-2xl bg-primary/10 text-primary"><Icon size={20} aria-hidden /></span><h2 className="min-w-0 flex-1 text-lg font-bold text-foreground">{title}</h2>{action && <button type="button" onClick={onAction} className="min-h-11 rounded-xl px-2 text-sm font-semibold text-primary hover:bg-primary/5 focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-ring">{action} <ChevronRight size={16} className="inline" aria-hidden /></button>}</header>{children}</section>; }
function QuickAction({ icon: Icon, label, onClick }: { icon: typeof Activity; label: string; onClick: () => void }) { return <button type="button" onClick={onClick} className="flex min-h-20 items-center gap-4 rounded-2xl border border-white bg-white/90 p-4 text-left font-semibold shadow-[0_8px_24px_rgba(70,45,96,.07)] transition hover:-translate-y-0.5 hover:border-primary/20 hover:shadow-md focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-ring"><span className="flex h-11 w-11 items-center justify-center rounded-xl bg-primary/10 text-primary"><Icon size={22} aria-hidden /></span>{label}</button>; }
function ToolCard({ icon: Icon, title, text, onClick }: { icon: typeof Activity; title: string; text: string; onClick: () => void }) { return <button type="button" onClick={onClick} className="flex min-h-24 items-center gap-3 rounded-2xl bg-[linear-gradient(135deg,rgba(239,230,251,.95),rgba(250,248,255,.95))] p-4 text-left transition hover:shadow-sm focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-ring"><Icon className="shrink-0 text-primary" aria-hidden /><span><span className="block font-bold text-primary">{title}</span><span className="mt-1 block text-xs text-muted-foreground">{text}</span></span><ChevronRight className="ml-auto shrink-0 text-primary" aria-hidden /></button>; }
function OwnerAvatar({ owner, size = 'h-7 w-7' }: { owner: TutorHomeLinkedUser; size?: string }) { const avatar = owner.avatar?.trim(); const image = avatar && (/^(https?:|data:image\/|\/)/.test(avatar) || /\.(png|jpe?g|webp|svg)$/i.test(avatar)); return <span className={`inline-flex ${size} shrink-0 items-center justify-center overflow-hidden rounded-full bg-primary/10 text-xs font-bold text-primary`} aria-hidden>{image ? <img src={avatar} alt="" className="h-full w-full object-cover" /> : avatar || owner.name.slice(0, 1)}</span>; }
function PersonChip({ owner }: { owner: TutorHomeLinkedUser }) { return <span className="inline-flex max-w-28 items-center gap-1.5 rounded-full bg-primary/[0.065] py-1 pl-1 pr-2 text-xs font-semibold text-primary"><OwnerAvatar owner={owner} size="h-6 w-6" /><span className="truncate">{owner.name.split(' ')[0]}</span></span>; }
function EventContext({ owner }: { owner?: TutorHomeLinkedUser }) { return owner ? <PersonChip owner={owner} /> : <span className="rounded-full bg-muted px-2 py-1 text-xs font-semibold text-muted-foreground">Agenda del tutor</span>; }
function Legend({ color, label, value }: { color: string; label: string; value: number }) { return <div className="flex items-center gap-2"><span className={`h-2.5 w-2.5 rounded-full ${color}`} /><span className="flex-1 text-muted-foreground">{label}</span><span className="font-semibold tabular-nums">{value}%</span></div>; }
function Metric({ value, label }: { value: string | number; label: string }) { return <div className="text-center"><p className="text-xl font-bold text-primary tabular-nums">{value}</p><p className="text-[11px] text-muted-foreground">{label}</p></div>; }
function EmptyState({ text }: { text: string }) { return <p className="rounded-2xl border border-dashed border-border p-5 text-center text-sm text-muted-foreground">{text}</p>; }
