import { useEffect, useMemo, useState } from 'react';
import { Mail, MessageCircle, Search, Stethoscope } from 'lucide-react';
import { Input } from '@/components/ui/input';
import { Button } from '@/components/ui/button';
import { fetchProfessionalDirectory, type ProfessionalPublicProfile } from '@/data/api';

export default function ProfessionalDirectory() {
  const [items, setItems] = useState<ProfessionalPublicProfile[]>([]);
  const [query, setQuery] = useState('');
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState(false);
  useEffect(() => { fetchProfessionalDirectory().then(setItems).catch(() => setError(true)).finally(() => setLoading(false)); }, []);
  const filtered = useMemo(() => { const q = query.trim().toLocaleLowerCase('es'); return !q ? items : items.filter(item => [item.nombre, item.profesion, item.especialidad, item.modalidad].some(value => value?.toLocaleLowerCase('es').includes(q))); }, [items, query]);
  return <div className="space-y-4"><div><h2 className="font-heading text-xl font-bold">Directorio profesional</h2><p className="text-sm text-muted-foreground">Profesionales validados que eligieron publicar su perfil.</p></div><div className="relative"><Search size={16} className="absolute left-3 top-1/2 -translate-y-1/2 text-muted-foreground" /><Input className="pl-9" value={query} onChange={e => setQuery(e.target.value)} placeholder="Buscar por nombre, especialidad o modalidad" /></div>{loading && <div className="rounded-xl border p-8 text-center text-sm text-muted-foreground">Cargando profesionales...</div>}{error && <div className="rounded-xl border border-destructive/30 bg-destructive/5 p-5 text-sm text-destructive">No pudimos cargar el directorio.</div>}{!loading && !error && filtered.length === 0 && <div className="rounded-xl border border-dashed p-8 text-center"><Stethoscope className="mx-auto mb-2 text-primary" /><p className="font-medium">No encontramos profesionales</p><p className="text-sm text-muted-foreground">Proba con otra búsqueda.</p></div>}<div className="grid gap-4 md:grid-cols-2">{filtered.map(profile => <article key={profile.id} className="rounded-xl border bg-card p-4"><div className="flex items-start gap-3"><div className="flex h-11 w-11 items-center justify-center rounded-full bg-primary/10 text-primary"><Stethoscope size={20} /></div><div className="min-w-0"><h3 className="font-semibold">{profile.nombre}</h3><p className="text-sm text-primary">{profile.especialidad || profile.profesion}</p><p className="text-xs text-muted-foreground">{[profile.institucion, profile.modalidad].filter(Boolean).join(' · ')}</p></div></div>{profile.descripcion && <p className="mt-3 text-sm text-muted-foreground line-clamp-3">{profile.descripcion}</p>}<div className="mt-3 grid grid-cols-2 gap-2 text-xs"><div className="rounded-lg bg-muted/40 p-2"><span className="text-muted-foreground">Disponibilidad</span><p className="font-medium">{profile.disponibilidad || 'A coordinar'}</p></div><div className="rounded-lg bg-muted/40 p-2"><span className="text-muted-foreground">Sesion</span><p className="font-medium">{profile.precio_sesion == null ? 'Consultar' : `$${profile.precio_sesion}`}</p></div></div><div className="mt-4 flex gap-2">{profile.correo_contacto && <Button size="sm" variant="outline" className="flex-1" asChild><a href={`mailto:${profile.correo_contacto}`}><Mail size={14} className="mr-2" />Email</a></Button>}{profile.whatsapp_contacto && <Button size="sm" className="flex-1" asChild><a href={`https://wa.me/${profile.whatsapp_contacto.replace(/\D/g, '')}`} target="_blank" rel="noreferrer"><MessageCircle size={14} className="mr-2" />WhatsApp</a></Button>}</div></article>)}</div></div>;
}
