import { useEffect, useMemo, useState } from 'react';
import { Button } from '@/components/ui/button';
import { Input } from '@/components/ui/input';
import MiniGame from '@/components/MiniGame';
import { fetchPictograms, fetchRoutinesForUser, type DayRoutine, type Pictogram, type User } from '@/data/api';
import { createRoutineCard, emptyRoutineSequence, snapshotRoutine, type RoutineCard, type RoutineRound, type RoutineSequenceData, type RoutineSequenceMode, validateRoutineSequence } from '@/data/routineSequence';

const MODE_LABELS: Record<RoutineSequenceMode, string> = { order: 'Armá tu rutina', next: '¿Qué viene después?', missing: 'Paso que falta', detective: 'Detective de rutinas', 'plan-b': 'Plan B' };

function defaultRounds(mode: RoutineSequenceMode, cards: RoutineCard[], stepIds: string[]): RoutineRound[] | undefined {
  if (mode === 'order') return undefined;
  const options = stepIds.slice(1, Math.min(4, stepIds.length));
  if (options.length < 2) options.push(stepIds[0]);
  if (mode === 'next') return [{ id: crypto.randomUUID(), sequenceIds: [stepIds[0]], optionIds: options, acceptedIds: [stepIds[1]] }];
  if (mode === 'missing') return [{ id: crypto.randomUUID(), sequenceIds: stepIds.filter(id => id !== stepIds[1]), optionIds: [stepIds[1], stepIds[stepIds.length - 1]], acceptedIds: [stepIds[1]] }];
  if (mode === 'detective') return [{ id: crypto.randomUUID(), sequenceIds: stepIds, conflictId: stepIds[1], optionIds: [stepIds[0], stepIds[stepIds.length - 1]], acceptedIds: [stepIds[stepIds.length - 1]], explanation: 'Este paso se puede reemplazar por una alternativa más segura o adecuada.' }];
  return [{ id: crypto.randomUUID(), prompt: 'Algo cambió hoy. ¿Qué alternativa puede ayudar?', optionIds: stepIds.slice(0, Math.min(4, stepIds.length)), acceptedIds: [stepIds[0]], explanation: 'Puede haber más de una forma válida de adaptar la rutina o pedir ayuda.' }];
}

export default function RoutineSequenceEditor({ value, onChange, assignableUsers, onSourceUserChange }: { value?: RoutineSequenceData; onChange: (value: RoutineSequenceData) => void; assignableUsers: User[]; onSourceUserChange: (id?: string) => void }) {
  const data = value || emptyRoutineSequence();
  const [preview, setPreview] = useState(false);
  const [sourceUserId, setSourceUserId] = useState(data.sourceRoutine?.sourceUserId || '');
  const [routines, setRoutines] = useState<DayRoutine[]>([]);
  const [selectedRoutineId, setSelectedRoutineId] = useState('');
  const [rangeStart, setRangeStart] = useState(0);
  const [rangeEnd, setRangeEnd] = useState(7);
  const [pictoCardId, setPictoCardId] = useState<string | null>(null);
  const [pictoQuery, setPictoQuery] = useState('');
  const [pictograms, setPictograms] = useState<Pictogram[]>([]);
  const cards = useMemo(() => new Map(data.cards.map(card => [card.id, card])), [data.cards]);
  const update = (patch: Partial<RoutineSequenceData>) => onChange({ ...data, ...patch });
  const updateCard = (id: string, patch: Partial<RoutineCard>) => update({ cards: data.cards.map(card => card.id === id ? { ...card, ...patch } : card) });

  useEffect(() => { if (!sourceUserId) { setRoutines([]); return; } fetchRoutinesForUser(sourceUserId).then(setRoutines); }, [sourceUserId]);
  useEffect(() => { if (!pictoQuery.trim()) { setPictograms([]); return; } const timer = window.setTimeout(() => fetchPictograms({ search: pictoQuery, limit: 8 }).then(items => setPictograms(items.slice(0, 8))).catch(() => setPictograms([])), 300); return () => clearTimeout(timer); }, [pictoQuery]);

  const setMode = (mode: RoutineSequenceMode) => update({ mode, rounds: defaultRounds(mode, data.cards, data.stepIds) });
  const addCard = () => { if (data.stepIds.length >= 8) return; const card = createRoutineCard('Nuevo paso'); update({ cards: [...data.cards, card], stepIds: [...data.stepIds, card.id], acceptedOrders: [[...data.stepIds, card.id]], rounds: defaultRounds(data.mode, [...data.cards, card], [...data.stepIds, card.id]) }); };
  const removeCard = (id: string) => { if (data.stepIds.length <= 3) return; const stepIds = data.stepIds.filter(item => item !== id); const nextCards = data.cards.filter(card => card.id !== id); update({ cards: nextCards, stepIds, acceptedOrders: [stepIds], rounds: defaultRounds(data.mode, nextCards, stepIds) }); };
  const move = (index: number, direction: -1 | 1) => { const target = index + direction; if (target < 0 || target >= data.stepIds.length) return; const stepIds = [...data.stepIds]; [stepIds[index], stepIds[target]] = [stepIds[target], stepIds[index]]; update({ stepIds, acceptedOrders: [stepIds, ...data.acceptedOrders.filter(order => order.join('|') !== data.stepIds.join('|'))] }); };
  const importRoutine = () => {
    const routine = routines.find(item => item.id === selectedRoutineId); if (!routine) return;
    const start = Math.max(0, Math.min(rangeStart, routine.items.length - 1)); const end = Math.min(routine.items.length, Math.max(start + 3, rangeEnd + 1));
    let snapshot; try { snapshot = snapshotRoutine(routine, sourceUserId, start, end - 1); } catch { return; }
    onChange({ ...data, ...snapshot, acceptedOrders: [snapshot.stepIds], rounds: defaultRounds(data.mode, snapshot.cards, snapshot.stepIds) });
    onSourceUserChange(sourceUserId);
  };
  const error = validateRoutineSequence(data);

  return <div className="space-y-4 rounded-xl border border-primary/20 bg-primary/5 p-3">
    <div className="grid gap-3 sm:grid-cols-3"><label className="text-xs font-semibold">Modo<select className="mt-1 h-10 w-full rounded-md border bg-background px-2" value={data.mode} onChange={event => setMode(event.target.value as RoutineSequenceMode)}>{Object.entries(MODE_LABELS).map(([id, label]) => <option key={id} value={id}>{label}</option>)}</select></label><label className="text-xs font-semibold">Nivel de apoyo<select className="mt-1 h-10 w-full rounded-md border bg-background px-2" value={data.supportLevel} onChange={event => update({ supportLevel: event.target.value as RoutineSequenceData['supportLevel'] })}><option value="initial">Inicial</option><option value="intermediate">Intermedio</option><option value="advanced">Avanzado</option></select></label><label className="flex items-end gap-2 pb-2 text-xs font-semibold"><input type="checkbox" checked={data.hintsEnabled} onChange={event => update({ hintsEnabled: event.target.checked })} /> Permitir pistas</label></div>
    <label className="text-xs font-semibold">Consigna<Input className="mt-1" value={data.prompt} onChange={event => update({ prompt: event.target.value })} /></label>
    {assignableUsers.length > 0 && <div className="space-y-2 rounded-lg border bg-background p-3"><p className="text-sm font-bold">Copiar una rutina real</p><div className="grid gap-2 sm:grid-cols-2"><select className="h-10 rounded-md border px-2" value={sourceUserId} onChange={event => { setSourceUserId(event.target.value); setSelectedRoutineId(''); onSourceUserChange(undefined); }}><option value="">Elegí un perteneciente</option>{assignableUsers.map(user => <option key={user.id} value={user.id}>{user.name}</option>)}</select><select className="h-10 rounded-md border px-2" value={selectedRoutineId} onChange={event => { setSelectedRoutineId(event.target.value); const routine = routines.find(item => item.id === event.target.value); setRangeStart(0); setRangeEnd(Math.min(7, (routine?.items.length || 1) - 1)); }}><option value="">Elegí una rutina</option>{routines.map(routine => <option key={routine.id} value={routine.id}>{routine.name} ({routine.items.length})</option>)}</select></div>{selectedRoutineId && <div className="flex flex-wrap items-end gap-2"><label className="text-xs">Desde<Input type="number" min={1} value={rangeStart + 1} onChange={event => setRangeStart(Math.max(0, Number(event.target.value) - 1))} /></label><label className="text-xs">Hasta<Input type="number" min={3} max={routines.find(item => item.id === selectedRoutineId)?.items.length || 8} value={rangeEnd + 1} onChange={event => setRangeEnd(Number(event.target.value) - 1)} /></label><Button type="button" onClick={importRoutine}>Crear instantánea</Button></div>}<p className="text-xs text-muted-foreground">Elegí un tramo contiguo de 3 a 8 pasos. La copia sólo podrá asignarse a este perteneciente.</p></div>}
    <div className="space-y-2"><div className="flex items-center justify-between"><p className="text-sm font-bold">Tarjetas ({data.stepIds.length}/8)</p><Button type="button" size="sm" variant="outline" onClick={addCard} disabled={data.stepIds.length >= 8}>Agregar paso</Button></div>{data.stepIds.map((id, index) => { const card = cards.get(id)!; return <div key={id} className="grid gap-2 rounded-lg border bg-background p-2 sm:grid-cols-[auto_1fr_80px_auto]"><div className="flex gap-1"><button type="button" className="min-h-11 min-w-11 rounded border" disabled={index === 0} onClick={() => move(index, -1)}>▲</button><button type="button" className="min-h-11 min-w-11 rounded border" disabled={index === data.stepIds.length - 1} onClick={() => move(index, 1)}>▼</button></div><Input value={card.text} aria-label={`Texto del paso ${index + 1}`} onChange={event => updateCard(id, { text: event.target.value, accessibleLabel: event.target.value })} /><Input value={card.emoji || ''} aria-label={`Emoji del paso ${index + 1}`} onChange={event => updateCard(id, { emoji: event.target.value })} /><div className="flex gap-1"><Button type="button" size="sm" variant="outline" onClick={() => setPictoCardId(pictoCardId === id ? null : id)}>Pictograma</Button><Button type="button" size="sm" variant="ghost" disabled={data.stepIds.length <= 3} onClick={() => removeCard(id)}>×</Button></div>{pictoCardId === id && <div className="space-y-2 sm:col-span-4"><Input placeholder="Buscar pictograma" value={pictoQuery} onChange={event => setPictoQuery(event.target.value)} /><div className="grid grid-cols-4 gap-2">{pictograms.map(pictogram => <button type="button" key={pictogram.id} className="rounded border p-1 text-xs" onClick={() => { updateCard(id, { pictogramId: String(pictogram.id), imageUrl: pictogram.imageUrl, accessibleLabel: pictogram.name }); setPictoCardId(null); }}><img src={pictogram.imageUrl} alt="" className="mx-auto h-12 w-12 object-contain" />{pictogram.name}</button>)}</div></div>}</div>; })}</div>
    {data.mode === 'order' && data.acceptedOrders.length > 1 && <div className="space-y-1 rounded-lg border bg-background p-3"><p className="text-xs font-bold">Órdenes alternativos aceptados</p>{data.acceptedOrders.slice(1).map((order, index) => <div key={order.join('|')} className="flex items-center gap-2 text-xs"><span className="flex-1">{order.map(id => cards.get(id)?.text).join(' → ')}</span><Button type="button" size="sm" variant="ghost" onClick={() => update({ acceptedOrders: data.acceptedOrders.filter((_, orderIndex) => orderIndex !== index + 1) })}>Quitar</Button></div>)}</div>}
    {data.mode !== 'order' && <RoundEditor data={data} onChange={onChange} />}
    <div className="flex items-center justify-between"><p role={error ? 'alert' : undefined} className={`text-xs ${error ? 'text-destructive' : 'text-green-700'}`}>{error || 'Configuración válida'}</p><Button type="button" variant="outline" disabled={Boolean(error)} onClick={() => setPreview(value => !value)}>{preview ? 'Cerrar vista previa' : 'Vista previa jugable'}</Button></div>
    {preview && !error && <div className="rounded-xl border bg-background p-4"><MiniGame gameType="routine-sequence" gameData={{ routineSequence: data }} onFinish={() => setPreview(false)} /></div>}
  </div>;
}

function RoundEditor({ data, onChange }: { data: RoutineSequenceData; onChange: (data: RoutineSequenceData) => void }) {
  const cards = new Map(data.cards.map(card => [card.id, card])); const rounds = data.rounds || [];
  const updateRound = (index: number, patch: Partial<RoutineRound>) => onChange({ ...data, rounds: rounds.map((round, i) => i === index ? { ...round, ...patch } : round) });
  return <div className="space-y-3"><div className="flex items-center justify-between"><p className="text-sm font-bold">Rondas y respuestas</p><Button type="button" size="sm" variant="outline" onClick={() => onChange({ ...data, rounds: [...rounds, { ...rounds[rounds.length - 1], id: crypto.randomUUID(), prompt: '' }] })}>Agregar ronda</Button></div>{rounds.map((round, index) => <div key={round.id} className="space-y-2 rounded-lg border bg-background p-3"><div className="flex gap-2"><Input placeholder="Consigna de la ronda" value={round.prompt || ''} onChange={event => updateRound(index, { prompt: event.target.value })} /><Button type="button" variant="ghost" disabled={rounds.length === 1} onClick={() => onChange({ ...data, rounds: rounds.filter((_, i) => i !== index) })}>Quitar</Button></div>{data.mode === 'detective' && <label className="text-xs">Paso incorrecto o inseguro<select className="ml-2 h-9 rounded border" value={round.conflictId} onChange={event => updateRound(index, { conflictId: event.target.value })}>{round.sequenceIds?.map(id => <option key={id} value={id}>{cards.get(id)?.text}</option>)}</select></label>}<p className="text-xs font-semibold">Opciones (elegí entre 2 y 4)</p><div className="grid gap-1 sm:grid-cols-2">{data.cards.map(card => <label key={card.id} className="flex min-h-11 items-center gap-2 rounded border p-2 text-xs"><input type="checkbox" checked={round.optionIds.includes(card.id)} disabled={!round.optionIds.includes(card.id) && round.optionIds.length >= 4} onChange={event => { const optionIds = event.target.checked ? [...round.optionIds, card.id] : round.optionIds.filter(id => id !== card.id); updateRound(index, { optionIds, acceptedIds: round.acceptedIds.filter(id => optionIds.includes(id)) }); }} />{card.text}</label>)}</div><p className="text-xs font-semibold">Respuestas aceptables</p><div className="grid gap-1 sm:grid-cols-2">{round.optionIds.map(id => <label key={id} className="flex min-h-11 items-center gap-2 rounded border p-2 text-xs"><input type="checkbox" checked={round.acceptedIds.includes(id)} onChange={event => updateRound(index, { acceptedIds: event.target.checked ? [...round.acceptedIds, id] : round.acceptedIds.filter(item => item !== id) })} />{cards.get(id)?.text}</label>)}</div>{(data.mode === 'detective' || data.mode === 'plan-b') && <textarea className="w-full rounded border p-2 text-sm" value={round.explanation || ''} placeholder="Explicación breve, descriptiva y no culpabilizante" onChange={event => updateRound(index, { explanation: event.target.value })} />}</div>)}</div>;
}
