import { useEffect } from 'react';
import { createPortal } from 'react-dom';
import { AnimatePresence, motion, useReducedMotion } from 'framer-motion';
import { Activity, CalendarDays, FileText, FolderOpen, Heart, Info, MessageCircle, Settings, Sparkles, Stethoscope, Users, X } from 'lucide-react';
import AccountDropdown from '@/components/shared/AccountDropdown';

export type ProfessionalTab = 'home' | 'calendar' | 'patients' | 'chat' | 'notifications' | 'documents' | 'create' | 'pictograms' | 'pictogramCatalog' | 'resources' | 'recentActivity' | 'emotionalStatus' | 'reports' | 'tools' | 'profile' | 'about';
type Navigate = (tab: ProfessionalTab) => void;
type Permissions = { sessions: boolean; activities: boolean; chat: boolean };

const groups = (permissions: Permissions) => [
  { title: 'Principal', items: [{ id: 'home' as const, label: 'Inicio', icon: Stethoscope }, ...(permissions.sessions ? [{ id: 'calendar' as const, label: 'Calendario y sesiones', icon: CalendarDays }] : []), { id: 'patients' as const, label: 'Pacientes', icon: Users }, ...(permissions.chat ? [{ id: 'chat' as const, label: 'Chats', icon: MessageCircle }] : [])] },
  { title: 'Trabajo', items: [{ id: 'documents' as const, label: 'Documentos y notas', icon: FolderOpen }, ...(permissions.activities ? [{ id: 'create' as const, label: 'Actividades', icon: Activity }] : []), { id: 'resources' as const, label: 'Recursos y herramientas', icon: Sparkles }] },
  { title: 'Seguimiento', items: [{ id: 'recentActivity' as const, label: 'Actividad reciente', icon: Activity }, { id: 'emotionalStatus' as const, label: 'Estado emocional', icon: Heart }, { id: 'reports' as const, label: 'Reportes', icon: FileText }] },
  { title: 'TÁNDEM', items: [{ id: 'about' as const, label: 'Acerca de TÁNDEM', icon: Info }] },
];

type DrawerProps = { open: boolean; active: ProfessionalTab; permissions: Permissions; onClose: () => void; onNavigate: Navigate; onLogout: () => void };
export function ProfessionalDrawer({ open, active, permissions, onClose, onNavigate }: DrawerProps) {
  useEscape(open, onClose);
  const reduce = useReducedMotion();
  return <AnimatePresence>{open && <motion.div className="fixed inset-0 z-[70] bg-slate-950/40 backdrop-blur-sm" initial={{ opacity: 0 }} animate={{ opacity: 1 }} exit={{ opacity: 0 }} onClick={onClose}><motion.aside role="dialog" aria-modal="true" aria-label="Navegación profesional" className="flex h-full w-[min(88vw,22rem)] flex-col overflow-y-auto rounded-r-[32px] border-r border-violet-100 bg-[#fbf9ff] p-5 shadow-2xl" initial={reduce ? { opacity: 0 } : { x: '-100%' }} animate={{ x: 0, opacity: 1 }} exit={reduce ? { opacity: 0 } : { x: '-100%' }} transition={{ duration: reduce ? .1 : .23 }} onClick={event => event.stopPropagation()}><DrawerHeader title="Menú profesional" onClose={onClose} /><nav className="space-y-5">{groups(permissions).map(group => <NavGroup key={group.title} title={group.title} items={group.items} active={active} onNavigate={onNavigate} hideOnMobile={group.title === 'Principal' || group.title === 'Trabajo'} />)}</nav></motion.aside></motion.div>}</AnimatePresence>;
}

export function ProfessionalAccountMenu({ open, onOpenChange, user, onNavigate, onLogout }: { open: boolean; onOpenChange: (open: boolean) => void; user: { name: string; avatar?: string | null }; onNavigate: Navigate; onLogout: () => void }) {
  return <AccountDropdown open={open} onOpenChange={onOpenChange} user={user} subtitle="Profesional" items={[{ id: 'profile', label: 'Mi perfil y configuración', icon: Settings, onSelect: () => onNavigate('profile') }, { id: 'about', label: 'Acerca de TÁNDEM', icon: Info, onSelect: () => onNavigate('about') }]} onLogout={onLogout} />;
}

export type ProfessionalQuickAction = 'activity' | 'resources' | 'documents' | 'pictogram';
export function ProfessionalQuickMenu({ open, onOpenChange, compactProgress, permissions, onAction }: { open: boolean; onOpenChange: (open: boolean) => void; compactProgress: number; permissions: Permissions; onAction: (action: ProfessionalQuickAction) => void }) {
  const reduce = useReducedMotion();
  const actions = [...(permissions.activities ? [{ id: 'activity' as const, label: 'Crear actividad', icon: Activity }] : []), { id: 'resources' as const, label: 'Recursos y herramientas', icon: Sparkles }, { id: 'documents' as const, label: 'Documentos y notas', icon: FolderOpen }, { id: 'pictogram' as const, label: 'Crear pictograma IA', icon: Sparkles }];
  const blurOverlay = typeof document !== 'undefined' ? createPortal(<AnimatePresence>{open && <motion.button type="button" aria-label="Cerrar acciones" className="fixed inset-0 z-40 h-full w-full bg-slate-950/15 backdrop-blur-[5px] lg:hidden" onClick={() => onOpenChange(false)} initial={{ opacity: 0 }} animate={{ opacity: 1 }} exit={{ opacity: 0 }} />}</AnimatePresence>, document.body) : null;
  return <>{blurOverlay}<AnimatePresence>{open && <motion.div role="dialog" aria-label="Acciones profesionales" className="fixed bottom-[calc(5.25rem+env(safe-area-inset-bottom))] left-0 right-0 z-[55] mx-auto grid w-[min(calc(100vw-3rem),23rem)] grid-cols-2 gap-2 lg:hidden" initial={reduce ? { opacity: 0 } : { opacity: 0, y: 18, scale: .96 }} animate={{ opacity: 1, y: 0, scale: 1 }} exit={{ opacity: 0, y: 10, scale: .97 }}>{actions.map(action => <button key={action.id} type="button" onClick={() => { onOpenChange(false); onAction(action.id); }} className="flex min-h-16 items-center gap-2 rounded-[22px] border border-white bg-white/90 px-3 text-left text-xs font-bold shadow-[0_7px_20px_rgba(77,45,112,.14)] focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-ring"><action.icon size={20} className="text-primary" aria-hidden />{action.label}</button>)}</motion.div>}</AnimatePresence><button type="button" onClick={() => onOpenChange(!open)} aria-label={open ? 'Cerrar acciones rápidas' : 'Abrir acciones rápidas'} aria-expanded={open} className="relative z-[60] inline-flex items-center justify-center rounded-full border-4 border-white bg-[#7447ac] text-white shadow-[0_7px_18px_rgba(92,52,139,.35)] focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-ring" style={{ width: 60 - compactProgress * 12, height: 60 - compactProgress * 12, transform: `translateY(${-8 + compactProgress * 4}px)` }}>{open ? <X size={25} aria-hidden /> : <img src="/tandem-mark.png" alt="" className="h-10 w-10 rounded-full object-cover" />}</button></>;
}

function NavGroup({ title, items, active, onNavigate, hideOnMobile = false }: { title: string; items: { id: ProfessionalTab; label: string; icon: typeof Users }[]; active: ProfessionalTab; onNavigate: Navigate; hideOnMobile?: boolean }) { return <section className={hideOnMobile ? 'max-lg:hidden' : undefined}><h3 className="mb-1 px-3 text-xs font-bold uppercase tracking-[.14em] text-muted-foreground">{title}</h3><div className="space-y-1">{items.map(item => <button key={item.id} type="button" onClick={() => onNavigate(item.id)} aria-current={active === item.id ? 'page' : undefined} className={`flex min-h-12 w-full items-center gap-3 rounded-2xl px-3 text-left text-sm font-semibold transition-colors focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-ring ${active === item.id ? 'bg-primary/10 text-primary' : 'text-foreground hover:bg-primary/5 hover:text-primary'}`}><item.icon size={20} aria-hidden />{item.label}</button>)}</div></section>; }
function DrawerHeader({ title, onClose }: { title: string; onClose: () => void }) { return <div className="mb-5 flex items-center justify-between"><h2 className="text-xl font-bold text-primary">{title}</h2><button type="button" onClick={onClose} aria-label="Cerrar" className="flex h-11 w-11 items-center justify-center rounded-full hover:bg-primary/10 focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-ring"><X aria-hidden /></button></div>; }
function useEscape(open: boolean, close: () => void) { useEffect(() => { if (!open) return; const onKey = (event: KeyboardEvent) => { if (event.key === 'Escape') close(); }; document.addEventListener('keydown', onKey); return () => document.removeEventListener('keydown', onKey); }, [open, close]); }
