import { useEffect } from 'react';
import { AnimatePresence, motion, useReducedMotion } from 'framer-motion';
import { Activity, Bell, CalendarDays, FileText, FolderOpen, Image, Info, LogOut, MessageCircle, Plus, Settings, Sparkles, Stethoscope, UserRound, Users, Wrench, X } from 'lucide-react';
import HeaderUserAvatar from '@/components/HeaderUserAvatar';

export type ProfessionalTab = 'home' | 'calendar' | 'patients' | 'chat' | 'notifications' | 'documents' | 'create' | 'pictograms' | 'pictogramCatalog' | 'resources' | 'reports' | 'tools' | 'profile' | 'about';
type Navigate = (tab: ProfessionalTab) => void;
type Permissions = { sessions: boolean; activities: boolean; chat: boolean };

const groups = (permissions: Permissions) => [
  { title: 'Principal', items: [{ id: 'home' as const, label: 'Inicio', icon: Stethoscope }, ...(permissions.sessions ? [{ id: 'calendar' as const, label: 'Calendario y sesiones', icon: CalendarDays }] : []), { id: 'patients' as const, label: 'Pacientes', icon: Users }, ...(permissions.chat ? [{ id: 'chat' as const, label: 'Chats', icon: MessageCircle }] : [])] },
  { title: 'Trabajo', items: [{ id: 'documents' as const, label: 'Documentos y notas', icon: FolderOpen }, ...(permissions.activities ? [{ id: 'create' as const, label: 'Actividades', icon: Activity }] : []), { id: 'resources' as const, label: 'Recursos y herramientas', icon: Sparkles }] },
  { title: 'Seguimiento', items: [{ id: 'reports' as const, label: 'Reportes', icon: FileText }, { id: 'notifications' as const, label: 'Notificaciones', icon: Bell }] },
  { title: 'Cuenta', items: [{ id: 'profile' as const, label: 'Mi perfil y configuración', icon: Settings }, { id: 'about' as const, label: 'Acerca de TÁNDEM', icon: Info }] },
];

type DrawerProps = { open: boolean; active: ProfessionalTab; permissions: Permissions; onClose: () => void; onNavigate: Navigate; onLogout: () => void };
export function ProfessionalDrawer({ open, active, permissions, onClose, onNavigate, onLogout }: DrawerProps) {
  useEscape(open, onClose); const reduce = useReducedMotion();
  return <AnimatePresence>{open && <motion.div className="fixed inset-0 z-[70] bg-slate-950/35 backdrop-blur-sm" initial={{ opacity: 0 }} animate={{ opacity: 1 }} exit={{ opacity: 0 }} onClick={onClose}><motion.aside aria-label="Navegación profesional" className="flex h-full w-[min(88vw,22rem)] flex-col overflow-y-auto rounded-r-[32px] bg-[#fbf9ff] p-5 shadow-2xl" initial={reduce ? { opacity: 0 } : { x: '-100%' }} animate={{ x: 0, opacity: 1 }} exit={reduce ? { opacity: 0 } : { x: '-100%' }} transition={{ duration: reduce ? .1 : .23 }} onClick={event => event.stopPropagation()}><DrawerHeader title="Menú" onClose={onClose} /><nav className="space-y-5">{groups(permissions).map(group => <NavGroup key={group.title} title={group.title} items={group.items} active={active} onNavigate={onNavigate} />)}</nav><Logout onClick={onLogout} /></motion.aside></motion.div>}</AnimatePresence>;
}

export function ProfessionalProfileDrawer({ open, active, user, permissions, onClose, onNavigate, onLogout }: DrawerProps & { user: { name: string; avatar?: string | null } }) {
  useEscape(open, onClose); const reduce = useReducedMotion();
  const profileGroups = [
    { title: 'Cuenta', items: [{ id: 'profile' as const, label: 'Mi perfil y configuración', icon: UserRound }, { id: 'notifications' as const, label: 'Notificaciones', icon: Bell }] },
    { title: 'Práctica', items: [{ id: 'patients' as const, label: 'Pacientes', icon: Users }, ...(permissions.sessions ? [{ id: 'calendar' as const, label: 'Calendario', icon: CalendarDays }] : []), { id: 'documents' as const, label: 'Documentos y notas', icon: FolderOpen }, { id: 'reports' as const, label: 'Reportes', icon: FileText }] },
    { title: 'Herramientas', items: [{ id: 'pictograms' as const, label: 'Pictogramas IA', icon: Sparkles }, { id: 'pictogramCatalog' as const, label: 'Pictogramas', icon: Image }, ...(permissions.chat ? [{ id: 'chat' as const, label: 'Chat', icon: MessageCircle }] : []), { id: 'tools' as const, label: 'Herramientas', icon: Wrench }, { id: 'about' as const, label: 'Acerca de TÁNDEM', icon: Info }] },
  ];
  return <AnimatePresence>{open && <div className="fixed inset-0 z-[75]"><motion.button type="button" aria-label="Cerrar perfil" onClick={onClose} className="absolute inset-0 h-full w-full bg-slate-950/25 backdrop-blur-[2px]" initial={{ opacity: 0 }} animate={{ opacity: 1 }} exit={{ opacity: 0 }} /><motion.aside role="dialog" aria-modal="true" aria-labelledby="professional-profile-title" className="absolute right-0 top-0 flex h-full w-[min(92vw,27rem)] flex-col overflow-y-auto rounded-l-[32px] bg-[#fbf9ff] p-5 shadow-2xl" initial={reduce ? { opacity: 0 } : { x: '100%' }} animate={{ x: 0, opacity: 1 }} exit={reduce ? { opacity: 0 } : { x: '100%' }} transition={{ duration: reduce ? .1 : .22 }}><DrawerHeader title="Perfil profesional" id="professional-profile-title" onClose={onClose} /><div className="mb-5 flex items-center gap-3 rounded-3xl border bg-card p-4"><HeaderUserAvatar avatar={user.avatar} name={user.name} /><div><p className="font-bold">{user.name}</p><p className="text-xs text-muted-foreground">Profesional</p></div></div><nav className="space-y-5">{profileGroups.map(group => <NavGroup key={group.title} title={group.title} items={group.items} active={active} onNavigate={onNavigate} />)}</nav><Logout onClick={onLogout} /></motion.aside></div>}</AnimatePresence>;
}

export type ProfessionalQuickAction = 'session' | 'note' | 'activity' | 'pictogram';
export function ProfessionalQuickMenu({ open, onOpenChange, compactProgress, permissions, onAction }: { open: boolean; onOpenChange: (open: boolean) => void; compactProgress: number; permissions: Permissions; onAction: (action: ProfessionalQuickAction) => void }) {
  const reduce = useReducedMotion();
  const actions = [...(permissions.sessions ? [{ id: 'session' as const, label: 'Nueva sesión', icon: CalendarDays }, { id: 'note' as const, label: 'Nota clínica', icon: FileText }] : []), ...(permissions.activities ? [{ id: 'activity' as const, label: 'Crear actividad', icon: Activity }] : []), { id: 'pictogram' as const, label: 'Crear pictograma IA', icon: Sparkles }];
  return <><AnimatePresence>{open && <><motion.button type="button" aria-label="Cerrar acciones" className="fixed inset-0 z-40 h-full w-full bg-white/10 backdrop-blur-[1px] lg:hidden" onClick={() => onOpenChange(false)} initial={{ opacity: 0 }} animate={{ opacity: 1 }} exit={{ opacity: 0 }} /><motion.div role="dialog" aria-label="Acciones profesionales" className="fixed bottom-[calc(5.25rem+env(safe-area-inset-bottom))] left-0 right-0 z-[55] mx-auto grid w-[min(calc(100vw-3rem),23rem)] grid-cols-2 gap-2 lg:hidden" initial={reduce ? { opacity: 0 } : { opacity: 0, y: 18, scale: .96 }} animate={{ opacity: 1, y: 0, scale: 1 }} exit={{ opacity: 0, y: 10, scale: .97 }}>{actions.map(action => <button key={action.id} type="button" onClick={() => { onOpenChange(false); onAction(action.id); }} className="flex min-h-16 items-center gap-2 rounded-[22px] border border-white bg-white/90 px-3 text-left text-xs font-bold shadow-[0_7px_20px_rgba(77,45,112,.14)] focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-ring"><action.icon size={20} className="text-primary" aria-hidden />{action.label}</button>)}</motion.div></>}</AnimatePresence><button type="button" onClick={() => onOpenChange(!open)} aria-label={open ? 'Cerrar acciones rápidas' : 'Abrir acciones rápidas'} aria-expanded={open} className="relative z-[60] inline-flex items-center justify-center rounded-full border-4 border-white bg-[#7447ac] text-white shadow-[0_7px_18px_rgba(92,52,139,.35)] focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-ring" style={{ width: 60 - compactProgress * 12, height: 60 - compactProgress * 12, transform: `translateY(${-8 + compactProgress * 4}px)` }}>{open ? <X size={25} aria-hidden /> : <img src="/tandem-mark.png" alt="" className="h-10 w-10 rounded-full object-cover" />}</button></>;
}

function NavGroup({ title, items, active, onNavigate }: { title: string; items: { id: ProfessionalTab; label: string; icon: typeof Users }[]; active: ProfessionalTab; onNavigate: Navigate }) { return <section><h3 className="mb-1 px-3 text-xs font-bold uppercase tracking-[.14em] text-muted-foreground">{title}</h3><div className="space-y-1">{items.map(item => <button key={item.id} type="button" onClick={() => onNavigate(item.id)} aria-current={active === item.id ? 'page' : undefined} className={`flex min-h-12 w-full items-center gap-3 rounded-2xl px-3 text-left text-sm font-semibold transition-colors focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-ring ${active === item.id ? 'bg-primary/10 text-primary' : 'hover:bg-primary/5'}`}><item.icon size={20} aria-hidden />{item.label}</button>)}</div></section>; }
function DrawerHeader({ title, id, onClose }: { title: string; id?: string; onClose: () => void }) { return <div className="mb-5 flex items-center justify-between"><h2 id={id} className="text-xl font-bold">{title}</h2><button type="button" onClick={onClose} aria-label="Cerrar" className="flex h-11 w-11 items-center justify-center rounded-full hover:bg-primary/10 focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-ring"><X aria-hidden /></button></div>; }
function Logout({ onClick }: { onClick: () => void }) { return <button type="button" onClick={onClick} className="mt-auto flex min-h-12 w-full items-center gap-3 border-t border-border px-3 pt-4 text-sm font-semibold text-primary"><LogOut size={20} aria-hidden />Cerrar sesión</button>; }
function useEscape(open: boolean, close: () => void) { useEffect(() => { if (!open) return; const onKey = (event: KeyboardEvent) => { if (event.key === 'Escape') close(); }; document.addEventListener('keydown', onKey); return () => document.removeEventListener('keydown', onKey); }, [open, close]); }
